### ISSUE TITLE
behavior when asset is not geo-referenced

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#118]
**On initial loading asset display page:**
- If asset is **NOT** geo-referenced, then disable the terrain.
- If asset is geo-referenced, then enable the terrain.

**On change of asset geo-location:**
(this applies only to assets that have no current geo-location)
- If user begins to enters geo-reference coordinates (latitude or longitude) in the geo-location pop-out menu, then enable terrain.

**Comment by 3DGISKing** [comment]
Dynamic enable/disable terrain results in an unwanted flick effect.

https://sandcastle.cesium.com/#c=bZBNSwMxEIb/ypBLt1CyeHa7iL0KCi16ySVNpm1wdlLysaWK/93shyDaHALzzvvMvEyvA/QOLxhgDYwX2GB0uZOvo1YpYcZ64zlpxxiUWN4rVrzVbI2OiVBqa3fe016Hx5yS5wLtMIRiV2IFh8wmOc9QLeFTMZRnPEdfQPLHapEm62IYOzSnMHKWX4LvnR3DzcFMQJ3wzQey85ZqQL+GT6xEE9OVsJ1mATy47uxDghyokrJO2J2p4LHeZ/OOSZoYfxY39W+0sa4HZ9c3DgCGdIylc8hEW/eBSrRNXfz/UPLaOj4+9xhIXwfb6a59mkQpZVOX8jaZpoP+mfwN

**Comment by 3DGISKing** [comment]
Please check above sandcastle link.

**Comment by outsider787** [comment]
I don't understand what that sandcastle demo is showing.
The terrain is displayed when the button is pressed, and the terrain is shown when the button is not pressed.

**Comment by 3DGISKing** [comment]
do not you feel a slight flicking effect?
If it is acceptable, I will continue.

**Comment by outsider787** [comment]
I need to make a correction to the original issue.
When I say "terrain" I mean "cesium globe + terrain"

**Comment by 3DGISKing** [comment]
Please check

**Comment by outsider787** [comment]
Testing

**Comment by outsider787** [comment]
Also set the `show` property of **sun** and **moon** to false

https://cesium.com/docs/cesiumjs-ref-doc/Moon.html
https://cesium.com/docs/cesiumjs-ref-doc/Sun.html

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
done

**Comment by outsider787** [comment]
I added a new custom field for each asset called `bg-color` 
Please link the background color to the hidden custom field `bg-color` 

**Logic**
- If the `bg-color` field is empty then display the current grey.
- If the `bg-color` field has a value, the use value listed for background color.

**Comment by 3DGISKing** [comment]
I see

**Comment by 3DGISKing** [comment]
done.
