### ISSUE TITLE
Social Share not work.

### ISSUE THREAD

**Issue by 3DGISKing** [Construkted-Reality/construkted_reality#124]
![image](https://user-images.githubusercontent.com/26606704/87883322-258a7900-ca39-11ea-9dfe-09f16a02e267.png)
I have linked my Github url in my profile setting page.
But when I click github icon on profile page, the page is simply refreshed.
Is this the original designed feature?

**Comment by outsider787** [comment]
I will ask Stefan to take a look

**Comment by Construkted-Reality** [comment]
Is this still an issue?

**Comment by 3DGISKing** [comment]
It corretly works.
