### ISSUE TITLE
Error Display

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#137]
Uploaded a new model to construkted, and this error comes up.
This model had around 28 million polygons, so it was split into 3 files. The split works.

If I upload a small model, where split code is not used, then there is no error.

https://construkted.com/asset/akwdvgb9lk7/
![image](https://user-images.githubusercontent.com/13057505/89741640-e613e300-da60-11ea-96f2-3faf7aadde55.png)

**Comment by 3DGISKing** [comment]
The site was not updated with the latest.
I have just updated from then I could not see this error no longer.

**Comment by outsider787** [comment]
What do you mean "The site was not updated with the latest."?
Do you mean the latest **Released** or the latest commit?

**Comment by 3DGISKing** [comment]
yes.
