### ISSUE TITLE
New file extension

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#141]
Currently the only allowed file extensions allowed are ZIP and LAZ.

I would like to add `.7z` and `.RAR` as acceptable file extensions.
The tile server should be able to handle those file extensions since we are using 7zip to decompress archives.
Need the frontend (WP) to allow upload of those file extensions, and need tile server to properly decompress those files.

**Comment by 3DGISKing** [comment]
done. please check.

**Comment by Construkted-Reality** [comment]
Also need to add the 7z and rar extensions to the WP front end, otherwise they are not allowed for upload.

![image](https://user-images.githubusercontent.com/13057505/98138806-79f32080-1e91-11eb-810d-ea7a395798a4.png)

**Comment by 3DGISKing** [comment]
where did you check? please check on gw.
