### ISSUE TITLE
Polygon and point cloud count

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#142]
The tile server is supposed to update the WP site with `mesh_polygon_count` for 3d mesh files, and `point_cloud_size` for point clouds.
That information is not being updated on WP site.

![image](https://user-images.githubusercontent.com/13057505/98036584-47411d80-1de8-11eb-8d27-270e95f68540.png)

**Comment by 3DGISKing** [comment]
did you see this bug in procution site too?

**Comment by 3DGISKing** [comment]
done. please check.

failed to connect to https://tile.api.construkted.com:5001
looks like that certificate is  expired
now only tile03 works
