### ISSUE TITLE
Add option for Cesium "Tile Inspector" Tool

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#143]
Add a check box option to the bottom of **Settings** side-menu called **"Display Tile Inspector"**
This checkbox should only be visible by an admin user only!

![image](https://user-images.githubusercontent.com/13057505/98037468-9dfb2700-1de9-11eb-9d60-9ebbaf70d101.png)

**Comment by Construkted-Reality** [comment]
This checkbox should toggle on/off the Cesium Tile Inspector tool.
https://sandcastle.cesium.com/?src=3D%20Tiles%20Inspector.html

![image](https://user-images.githubusercontent.com/13057505/98037629-e0246880-1de9-11eb-9438-99f335c299d7.png)

**Comment by 3DGISKing** [comment]
done. please check

**Comment by Construkted-Reality** [comment]
When I load a model, (even if I'm not admin) the tile inspector is running.
See video below.
When I move mouse over 3d tile, parts of the tile are highlited. That's due to the tile inspectror.


![error capture04](https://user-images.githubusercontent.com/13057505/98118655-8b303300-1e79-11eb-83c1-ab79b6aad922.gif)

**Comment by 3DGISKing** [comment]
fixed.
