### ISSUE TITLE
embed display

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#145]
Embed view does not show the saved geo-location or saved view location.
Please make the "embed" version display geo-location and saved view location.

Left: Construkted Reality website  ______________________________________    Right: Embeded asset
![image](https://user-images.githubusercontent.com/13057505/100152018-0d57ba00-2e70-11eb-991e-f8eba5dfc2c8.png)

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
please check.

**Comment by Construkted-Reality** [comment]
The fix you created added some new text to the website.
Every page of the website shows the text **invalid url** at the top

![image](https://user-images.githubusercontent.com/13057505/100299717-58ea9080-2f62-11eb-9787-6333f33c486f.png)

**Comment by 3DGISKing** [comment]
Let me fix

**Comment by 3DGISKing** [comment]
Fixed. Let me know when you check all.
I need to merge issue working branch to master.

**Comment by Construkted-Reality** [comment]
Tested. Works.

**Comment by 3DGISKing** [comment]
I see.
