### ISSUE TITLE
Changes on production site

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#146]
Stefan made a few changes today on the production website.
The affected file was: 
`wp-content/themes/gowatch-child/includes/functions.php `  
**(if you see other modified files, please let me know)**

Please merge those changes into github repo.

**Comment by 3DGISKing** [comment]
Ok

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/100238285-f9dd4980-2f6a-11eb-95b6-60df05d5004f.png)

He made this. 
merged.
