### ISSUE TITLE
Incorrect links

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#148]
When clicking the asset author's name link, the wrong page is loaded.

![image](https://user-images.githubusercontent.com/13057505/100345992-2320c880-2fb1-11eb-879d-a89f4c0ca18e.png)

![image](https://user-images.githubusercontent.com/13057505/100346069-464b7800-2fb1-11eb-9c3b-a39ea0b5745d.png)

**Comment by stefanciorici** [comment]
Fixed. https://github.com/Construkted-Reality/construkted_reality/commit/430fa9d58bf27710ccef15b5e35bfa520a9f1a84
