### ISSUE TITLE
Go to asset.

### ISSUE THREAD

**Issue by 3DGISKing** [Construkted-Reality/construkted_reality#155]
There is no way to go to the asset when we are far from the position of the asset.

**Comment by Construkted-Reality** [comment]
I don't understand.

**Comment by 3DGISKing** [comment]
let 's say that the camera position is far from the asset's location so he does not see the asset now.
then how can he navigate the position of the asset?

**Comment by Construkted-Reality** [comment]
The user can always re-load the page

**Comment by 3DGISKing** [comment]
Of course, he can, but not convenient.
