### ISSUE TITLE
Add Cesium 3D tile import functionality

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#157]
Reality Capture, MetasShape and others can output 3d tiles.
Allow for the uploading of the 3d tiles exported by those software to be ingested into Contrukted Reality.

The format is a zip file which includes a json file and all the 3d tiles.

**Comment by Construkted-Reality** [comment]
Added the option for 3d tile upload in Front End uploading page
![image](https://user-images.githubusercontent.com/13057505/111033363-e3a2ae80-83de-11eb-80bb-8cec3b3fd412.png)

**Comment by 3DGISKing** [comment]
We assumed that the tileset JSON file's name is the same as "tileset.json" so far.
But in the tiled data generated by the RealityCapture, it's not true.
So we need to store the tileset JSON file's name.

https://gw3.construkted.com/asset/aqq5ex9gq95/

![image](https://user-images.githubusercontent.com/26606704/111277117-0c42d680-8673-11eb-9edf-dddf230e6db1.png)

![image](https://user-images.githubusercontent.com/26606704/111277304-46ac7380-8673-11eb-9aec-47a7ed0f2856.png)

**Comment by Construkted-Reality** [comment]
Or we rename the uploaded root json file to `tileset.json`

**Comment by 3DGISKing** [comment]
good idea. I agree.

**Comment by 3DGISKing** [comment]
tested asset

https://gw3.construkted.com/asset/a2f0d6h0ros/
https://gw3.construkted.com/asset/a4233e72xp2/

**Comment by 3DGISKing** [comment]
now the site was updated with branch issue28-3dtile-import.
please test.

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/111340652-cd814080-86b3-11eb-9978-077811139629.png)

I need to fix the frontend.

**Comment by 3DGISKing** [comment]
please test. gw site was updated with  issue28-3dtile-import branch.

**Comment by Construkted-Reality** [comment]
Strange behavior with [new model](https://upload.construkted.com/wl/?id=VpVaVuIBrpQIfIiDHNfMTbxxcjCwLH7n). Model disappears when zooming. 
Maybe something to do with the transform element in the json file?
![image](https://user-images.githubusercontent.com/13057505/111379033-07812100-8679-11eb-924f-9abfc5b0744f.png)

https://gw3.construkted.com/asset/auian763glq/

[Model for testing](https://upload.construkted.com/wl/?id=VpVaVuIBrpQIfIiDHNfMTbxxcjCwLH7n)

**Comment by Construkted-Reality** [comment]
The transform element in the `RealityCapture-Use_To_Test.zip` json file you used for testing is very different.
Do you understand the transform differences between the two files?

**Comment by Construkted-Reality** [comment]
I replaced the transform property with :
```
[
1.0, 0.0, 0.0, 0.0,
0.0, 1.0, 0.0, 0.0,
0.0, 0.0, 1.0, 0.0,
0.0, 0.0, 0.0, 1.0
]
```

and there is no more problem. Zooming works correctly.
https://gw3.construkted.com/asset/ae7thvkd6sy/

**Comment by 3DGISKing** [comment]
> Strange behavior with [new model](https://upload.construkted.com/wl/?id=VpVaVuIBrpQIfIiDHNfMTbxxcjCwLH7n). Model disappears when zooming.
> Maybe something to do with the transform property in the json file?
> ![image](https://user-images.githubusercontent.com/13057505/111379033-07812100-8679-11eb-924f-9abfc5b0744f.png)
> 
> https://gw3.construkted.com/asset/auian763glq/
> 
> [Model for testing](https://upload.construkted.com/wl/?id=VpVaVuIBrpQIfIiDHNfMTbxxcjCwLH7n)

Because the tileset is georeferenced, but construkted js judges that it's not georeferenced.

**Comment by 3DGISKing** [comment]
can not see lat/lon for [this](https://gw3.construkted.com/asset/ae7thvkd6sy/)

![image](https://user-images.githubusercontent.com/26606704/111493291-61b4db80-8778-11eb-8cc8-a0f5969df8ab.png)

**Comment by 3DGISKing** [comment]
please check.

**Comment by Construkted-Reality** [comment]
Testing

**Comment by Construkted-Reality** [comment]
1. The buttons for "Edit" and "Estimate Altitude" are functioning but are greyed out.
Please remove greyed out effect
![image](https://user-images.githubusercontent.com/13057505/111624577-3e168300-87c2-11eb-989b-aacb9cd60ac5.png)

2. 3D Tile file uploaded from MetaShape brings up an error.
Use this asset to test: https://gw3.construkted.com/asset/ab97x8zfzlw/
![image](https://user-images.githubusercontent.com/13057505/111625846-b3368800-87c3-11eb-9c55-0de1a005f7c0.png)

**Comment by 3DGISKing** [comment]
While the transform editor is activated, the user should not be able to change latitude, longitude abd altitude.
And also, he shouldn't click the estimate altitude button.

**Comment by 3DGISKing** [comment]
"3D Tile file uploaded from MetaShape brings up an error." 
fixed.

**Comment by Construkted-Reality** [comment]
> While the transform editor is activated, the user should not be able to change latitude, longitude abd altitude.
> And also, he shouldn't click the estimate altitude button.

Why should the user not be able to change lat, long, alt when the transform editor is active?

**Comment by Construkted-Reality** [comment]
When the transform editor is active, rename the button to "Exit visual editor", and the function is to exit transform editor. 

![image](https://user-images.githubusercontent.com/13057505/111644357-234e0980-87d6-11eb-8ad8-e7a34e00e6ec.png)

**Comment by 3DGISKing** [comment]
done. please see the site.
