### ISSUE TITLE
Desktop FLY reversed controls

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#164]
On my android phone, the screen buttons function correctly.
Desktop controls are reversed. 

The W and S keys are reversed, the A /D keys are reversed and the R/F keys are reversed

**Comment by 3DGISKing** [comment]
pls check

**Comment by Construkted-Reality** [comment]
On mobile, the on-screen buttons are also reversed.
Please correct the motion for mobile view as well.

![image](https://user-images.githubusercontent.com/13057505/107781889-6bc96180-6d16-11eb-886a-1fd4b1837260.png)

**Comment by 3DGISKing** [comment]
fixed. please check.

**Comment by Construkted-Reality** [comment]
Works
