### ISSUE TITLE
Mobile AR not working

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#165]
The AR mode on mobile (android) does not work.
It works on the production server (construkted.com) but not on the gw3 version.

I don't know if the new features made some changes that affected it's functionality or if the construkted.js split had an impact.

**Comment by 3DGISKing** [comment]
fixed. please check and let me know.

**Comment by Construkted-Reality** [comment]
Thank you.
There are still some issues that I noticed when testing.

**Comment by Construkted-Reality** [comment]
I will open new issues for each of them separately.
