### ISSUE TITLE
Can't change the altitude of asset.

### ISSUE THREAD

**Issue by 3DGISKing** [Construkted-Reality/construkted_reality#173]
https://user-images.githubusercontent.com/26606704/109095036-f3bb5c80-7755-11eb-94c4-800d919bdf0b.mp4

**Comment by Construkted-Reality** [comment]
Please investigate and fix

**Comment by Construkted-Reality** [comment]
It looks like the asset is already geo-referenced. 
How do we override, or adjust the geo-reference data?

**Comment by 3DGISKing** [comment]
According to the original logic(code), it's not possible to override the longitude and latitude of the tileset.
It was designed to change only the altitude of a georeferenced tileset.
