### ISSUE TITLE
Navigation "Help menus" re-write/design

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#175]
Help menu overlay needs to convey the new methods of navigation to the user.
----------
**FLY Navigation**
FLY uses WASD to move left/right/forward/back and also uses R/F to move up/down  

**FPV Navigation**
For FPV and FLY moves, the SHIFT key is used to increase the movement speed.  

To enter FPV, the user needs to select the mode button before double-clicking to start.

**Comment by Construkted-Reality** [comment]
These are some of the issues to deal with:
![image](https://user-images.githubusercontent.com/13057505/109197501-1015c400-776b-11eb-8867-bba53fae76e5.png)

**Comment by 3DGISKing** [comment]
all are merged
testing result.

![image](https://user-images.githubusercontent.com/26606704/110961722-128f3500-838b-11eb-8f42-f9585de8da76.png)

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/110961880-3ce0f280-838b-11eb-801b-8eb6534f3855.png)
is this a tabbed window?
