### ISSUE TITLE
Update Cesium JS to latest version

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#177]
A few clients have requested the ability to display models that are under-water or underground.
Cesium has implemented a way to view underground assets in version 1.70
https://cesium.com/blog/2020/06/01/cesium-june-release/

To display the underground models, use this example to integrate the globe fade/translucency effect as camera moves closer to asset.
https://sandcastle.cesium.com/index.html?src=Globe%20Translucency.html

Asset that is under water. Use for testing 
https://gw3.construkted.com/asset/art1ve7lisi/

**Comment by Construkted-Reality** [comment]
If the asset has an altitude that is below the local globe terrain, draw a line.
Line should start at the asset, and end 200m above the local globe terrain.

![image](https://user-images.githubusercontent.com/13057505/109386208-2f296880-78c7-11eb-8359-e5d920d12372.png)

**Comment by 3DGISKing** [comment]
please check and let me know.

**Comment by Construkted-Reality** [comment]
Looks great.
Next we need to fade the terrain model like in this example.
https://sandcastle.cesium.com/index.html?src=Globe%20Translucency.html 

**Use these settings:** 

![image](https://user-images.githubusercontent.com/13057505/109493447-827ff000-7a5a-11eb-86ec-d8c4e648bc94.png)

**Comment by 3DGISKing** [comment]
We have a problem checking whether or not the tileset is underground.

![RdPiZEzdAz](https://user-images.githubusercontent.com/26606704/109584518-a0be1c80-7b3c-11eb-9c3f-019f4136a231.gif)

**Comment by 3DGISKing** [comment]
When we have enabled Cesium's world Terrain,  the point whose height is 0 is not on the sea surface.
When I set its height to -50m, it looks similar to the sea surface.

A similar topic was discussed in the below link.

[https://github.com/CesiumGS/cesium/issues/8414](https://github.com/CesiumGS/cesium/issues/8414)

**Comment by Construkted-Reality** [comment]
Make the **Translucency** and **Fade by distance** to always be on.
The default value for **Alpha** should be 25%

![image](https://user-images.githubusercontent.com/13057505/109806675-f9e88780-7bf2-11eb-8d57-fd0149c4441a.png)

**Comment by Construkted-Reality** [comment]
Please remove the "Wave Material".

**Comment by Construkted-Reality** [comment]
Make the yellow line disappear when the user is close to the asset. 

The line should fade with distance. 
When the user is close to the asset, then no line is shown.
As the user zooms out, the line should fade in so it becomes visible.

**Comment by Construkted-Reality** [comment]
Underground assets moved to new issue
https://github.com/Construkted-Reality/construkted_reality/issues/184
