### ISSUE TITLE
FLY speed difference

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#182]
The FLY speed is different for different assets. 

The FLY speed in this asset is fast
https://gw3.construkted.com/asset/l4sav2ekd8/ 

The FLY speed in this asset is very slow
https://gw3.construkted.com/asset/aucbzxw01n/ 

Why is there such a big difference in FLY speed? How is the FLY speed calculated?

**Comment by 3DGISKing** [comment]
Currently, the speed is calculated from the camera's height.
in the case of https://gw3.construkted.com/asset/l4sav2ekd8/, its altitude is a bit high than https://gw3.construkted.com/asset/aucbzxw01n/ so the FLY speed is determined more highly.

**Comment by Construkted-Reality** [comment]
I don't think the camera speed should be set by altitude.
It's too inconsistent between models.

Please remove the reference to `heightOfCamera` for camera movement in FLY mode.

**Comment by 3DGISKing** [comment]
done

**Comment by Construkted-Reality** [comment]
Is the FLY speed linked to the speed slider in the settings tab?

![image](https://user-images.githubusercontent.com/13057505/110111014-a35b8480-7d7d-11eb-8304-4a8bee4093d5.png)

**Comment by 3DGISKing** [comment]
yes

**Comment by Construkted-Reality** [comment]
I just tested and the speed slider and it does NOT affect the speed of FLY movement.

**Comment by 3DGISKing** [comment]
fixed

**Comment by Construkted-Reality** [comment]
Works!
