### ISSUE TITLE
Underground Assets

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#184]
Underground assets should have a checkbox added to the Geo-Location menu which controls the display of the yellow line and the terrain fade effect when getting closer to the terrain.

![image](https://user-images.githubusercontent.com/13057505/109990448-663cb700-7cd7-11eb-9084-ce7e1e44f72b.png)

**Comment by Construkted-Reality** [comment]
Custom field has been created in WP to store the checkbox value.
If there is no value, the code should assume the model is not underground.

![image](https://user-images.githubusercontent.com/13057505/109987478-a8182e00-7cd4-11eb-8725-29b6bd30b0c1.png)

**Comment by Construkted-Reality** [comment]
Checkbox added to wordpress.
When save button is pressed, save the status of the checkbox.

**Comment by 3DGISKing** [comment]
please check

**Comment by Construkted-Reality** [comment]
Works great!
