### ISSUE TITLE
Globe test - v2

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#185]
Keep old asset explorer from issue https://github.com/Construkted-Reality/construkted_reality/issues/168

### A new idea for Globe Asset Explorer

Create new "Asset Explorer Test V2" shortcode called `[asset-explorerV2][/asset-explorerV2]` 

Display the globe and at every geo-location there is an asset, place a round dot on the globe.
If the dot covers multiple assets, then show a dot with a number. The number indicates how many assets are under the dot area)

Something that looks like the [Open Heritage](https://openheritage3d.org/) map. (use as an example)

**Comment by 3DGISKing** [comment]
Based on rough checking open heritage source code,

A marker cluster contains a number of markers.  
A cluster has a center, bound, marker list.

1 create a cluster with the first cluster.
2 iterates other markers and does the following logic.
   find the closest cluster among cluster lists for the given marker.  
   if found, add the marker into the cluster and update cluster properties.
   if not, create a new cluster with it and update the cluster list.

**Comment by Construkted-Reality** [comment]
Please implement the marker cluster

**Comment by 3DGISKing** [comment]
sure.

**Comment by 3DGISKing** [comment]
found the most relevant sample.
https://cesium.com/docs/cesiumjs-ref-doc/EntityCluster.html
https://sandcastle.cesium.com/index.html?src=Clustering.html

**Comment by 3DGISKing** [comment]
Many discussions had been done for partial visibility of labels or billboards, but none of these did not help me.

https://community.cesium.com/t/labels-from-the-other-side-of-the-globe-hide-possibility/12505  
https://community.cesium.com/t/hide-billboards-behind-hills/11018/9  
https://community.cesium.com/t/points-labels-stuck-under-terrain/11141/13  

I solved this issue using scene.pickFromRay.
See the following sandcastle link.

[Demo](https://sandcastle.cesium.com/#c=pVRdb9owFP0rFi8kUmbCuo2IUrQO2hWpJVXLOk3LVJnkEqwaO7KdtGziv8/5ImnL9tI8RPG995xz7ZzrjEiUUXgEiU4Qh0c0AUXTDb4rYlbQCYv1RHBNKAcZdBz0J+AIaZDSRK6lyGgEclgDQwlEw3chWbQoSyzbCfjOPg54wEsprELggGMmloAjSPR6AUqfxqZY6Qpl2tEyhQIVChNHwDXVWxOvSIo1BYVJFFlFTwglQpmY4Pt2JkRq80X4EV5JsZlCLAGU9W4wwO7Rpw+e57130JGHPa/vDgYfPQe5ebs5FyNLYENUMeePhic9RF1DqLtOE85AahoS5ksa00b67lkYf/EXC/+qBVsDjdf6BlYggYewx108j+PJ5enV9f3Cv/9643+bT1sMEVVkyWBan+CUKk0Kqnm6WZojuvZvZ4vZ3dn9bH4+m88WP0rszqlPi3I9bG0woU/AbulvQEPUd9+k9PaNVr2+9E5INiAJTkAaE2kSw2RNeAyRMYaLXbd/oDYsK3KjnGUGdGm6NwaUlmWjk3H1h0uTieJnGa43+Oe4xRdRCWHuyMa3VVP7TFHegkiyfT6LN2RrlX05DV+lUrwyM8QSVMp0o1KOWELDh3PTd05heB3085e916MrZFUSEazMdEdWyWLbtevzjgQDzERc50rdUriaSVyMClZr8diMbStd+OxVepe/gCk4JNblotpS1z7+t9aKGPx/xJr8rtx15aWO0xkpvWUwrm36mW4SITVKJbMw7mnYJMxcZKq3TMMH0DhUqm5k1GtDRxHNEI1ODlyVKGREKZNZpawYq6AzHvVM/SsoEySiPPbNVcLINi9b98eXZRBjPOqZ5WGkFoItiXzB/Bc)

**Comment by 3DGISKing** [comment]
gw site was updated with this branch's changes.

https://gw3.construkted.com/asset-explorerv2-test/

**Comment by Construkted-Reality** [comment]
1. When the dot is clicked, the text should NOT replace the dot. The dot should remain visible.
Text should appear above the dot.

2. Dot diameter should be 3 times larger.

3. Change dot color to color pink

4. The billboard which displays the numbers should also be a dot/circle.

5. Clicking some dots do not display the text.
Text is displayed when zoomed out? 

![not_display](https://user-images.githubusercontent.com/13057505/111177587-c1e12d00-8580-11eb-90c0-08c2d27d7300.gif)

**Comment by 3DGISKing** [comment]
https://user-images.githubusercontent.com/26606704/111410327-7f038e80-8713-11eb-8496-da707d4b7b03.mp4

**Comment by Construkted-Reality** [comment]
Please commit changes so I can test.

**Comment by 3DGISKing** [comment]
the site was updated with the issue185-asset-explorer2 branch.
https://gw3.construkted.com/asset-explorerv2-test/

Please check quickly as possible as the branch is somehow old.

**Comment by Construkted-Reality** [comment]
Do you know what all the black dots are?

![image](https://user-images.githubusercontent.com/13057505/112838989-ab9c9c00-906b-11eb-8c45-539f88c58136.png)

**Comment by 3DGISKing** [comment]
Not. I have never seen them on my side.

**Comment by Construkted-Reality** [comment]
Rendering error on my computer.
Never mind

**Comment by 3DGISKing** [comment]
yes

**Comment by Construkted-Reality** [comment]
When I double click on a title the camera flies to the location, but the asset does not load.

**Comment by 3DGISKing** [comment]
I see. please check more and let me know.

**Comment by 3DGISKing** [comment]
test finished?

**Comment by Construkted-Reality** [comment]
1. When I double click on a title the camera flies to the location, but the asset does not load.
2. Single left-click on the dot with numbers should display a popup window listing the asset titles that are in that cluster. 
Double left-clicking the asset titles should fly the camera to the asset.
3. The dot should disappear when the camera is close to the asset 3d tiles.

**Comment by 3DGISKing** [comment]
I see.

**Comment by 3DGISKing** [comment]
please check

**Comment by 3DGISKing** [comment]
merged to the master. site is in the master branch.
