### ISSUE TITLE
Help menu icons

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#188]
The icons are missing in the help menu. 

![image](https://user-images.githubusercontent.com/26606704/110966726-8aac2980-8390-11eb-989d-fa43ccc255ba.png) 
 
![image](https://user-images.githubusercontent.com/13057505/110995640-b1df0880-8348-11eb-83ce-7dc5a55a910c.png)

**Comment by stefanciorici** [comment]
Added the icons here: https://github.com/Construkted-Reality/construkted_reality/tree/188_helpoverlayicons
