### ISSUE TITLE
Underwater asset line update

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#192]
When the altitude is changes in the geo-location tab, the start position of the yellow line does not get updated. 

![yellow-line-update-01](https://user-images.githubusercontent.com/13057505/111630949-40c8a680-87c9-11eb-99ff-15b5d5daedbf.gif)

**Comment by 3DGISKing** [comment]
it also should be updated when the altitude is changed by the transform editor.

**Comment by 3DGISKing** [comment]
please check.

**Comment by Construkted-Reality** [comment]
Checked.
Works.
