### ISSUE TITLE
3D Tile Underground asset yellow line termination

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#193]
The top of the yellow line should be above the ground.
This normally works correctly for a polygon mesh, but doesn't work correctly for 3D Tile. 

Test with this 3d tile asset: https://gw3.construkted.com/asset/a0coofkyr6h/

![yellow-line-update-02](https://user-images.githubusercontent.com/13057505/111631730-217e4900-87ca-11eb-8efe-58d8d5a07667.gif)

**Comment by 3DGISKing** [comment]
please check the site and let me know.

**Comment by Construkted-Reality** [comment]
Checked. Works.
