### ISSUE TITLE
Training and Scanning Service pages

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#194]
Create two new post types (with a way to edit the posts) along with 2 new pages displaying each of the post types.
- One post type is "Training Services". There are lots of companies worldwide that are offering 3d scanning training, and I want to create a repo listing companies that offer this type of training. 
This resource would be useful for people that want training.
 - The other post type is "Scanning Services". There are lots of companies worldwide which offer 3d scanning services. I want to create a repo listing these companies.
This resource would be useful for people needing to have 3d scanning done.

**Comment by stefanciorici** [comment]
Done: https://github.com/Construkted-Reality/construkted_reality/tree/issue_194_training_scan_services

You can use 2 different shortcodes for creating the grids:

[scanning_services]
[training_services]

It will create a grid of the specific custom post type. If you want to change the amount of posts shown add the **limit="NUMBER"** as a parameter (replace NUMBER with the actual number of items to be shown. _Ex: [scanning_services limit="12"]_

**Comment by Construkted-Reality** [comment]
The email field adds "https://" in front of the email address 

![image](https://user-images.githubusercontent.com/13057505/111776663-ab8ce700-8888-11eb-9c8b-e970fa752109.png)
