### ISSUE TITLE
"Underground Asset" checkbox

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#195]
"Underground asset" checkbox should only be visible if the asset is geo-referenced (lat/lon) 

![image](https://user-images.githubusercontent.com/13057505/111642036-1b8d6580-87d4-11eb-9b0d-069ac6e5c95f.png)

**Comment by 3DGISKing** [comment]
Then how would we handle the asset which is underground but not yet marked as "underground"?

**Comment by Construkted-Reality** [comment]
If the asset is not geo-referenced (Lat/Long is not defined or is zero) then the asset it not underground so we hide the option.
If the user enters a lat/long value, then the option becomes visible.

**Comment by 3DGISKing** [comment]
Please check the site.

**Comment by Construkted-Reality** [comment]
Works as expected
