### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by 3DGISKing** [Construkted-Reality/construkted_reality#196]
https://user-images.githubusercontent.com/26606704/111816793-38cb4c80-8918-11eb-910f-f5c0d866cbf0.mp4

**Comment by Construkted-Reality** [comment]
Can you share the link?

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/111819245-1555d100-891b-11eb-914a-60097fbe3e11.png)

This is because the site is not in the current issue's branch.
Maybe we need to have a reasonable co-working schema.
Let me switch to issue157-3dtile-import.

**Comment by 3DGISKing** [comment]
https://gw3.construkted.com/asset/aenez3ixl3k/
