### ISSUE TITLE
Estimate Altitude logic change

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#201]
"Place Asset on Terrain" button should use the bottom of the asset bounding box (lowest point of the bounding box) to position the asset on the terrain.

![image](https://user-images.githubusercontent.com/13057505/112314509-7cf37f80-8c7f-11eb-87cd-5505273423ec.png)

**Comment by 3DGISKing** [comment]
please check the site and let me know.

**Comment by Construkted-Reality** [comment]
When the "Place button on terrain" is pressed, the model doesn't get moved to new location.
Only the altitude value is updated.

**Comment by Construkted-Reality** [comment]
After more checking, most assets have the position updated correctly.
I will have to do more checking.

**Comment by Construkted-Reality** [comment]
This asset doesn't move when "Place asset on terrain" button is pushed.
https://gw3.construkted.com/asset/at5zihkx731/

Other assets work perfectly.

**Comment by 3DGISKing** [comment]
Asset at5zihkx731 's bounding volume information is rather different from others.
![image](https://user-images.githubusercontent.com/26606704/112595537-862e4900-8e45-11eb-88f3-c36a33fae517.png)

**Comment by 3DGISKing** [comment]
Most of all, the bounding volume of the root tile is OrientedBoundingBox, but in this asset, the boundingVolume  is not OrientedBoundingBox , BoundingSphere.

**Comment by Construkted-Reality** [comment]
Hmmm...
Do you have any ideas how to handle this edge case?

**Comment by 3DGISKing** [comment]
let me check why this happens in this asset.

**Comment by 3DGISKing** [comment]
![image](https://user-images.githubusercontent.com/26606704/112624529-b4715000-8e68-11eb-82c3-2d6c753a68e5.png)
This is normal.

**Comment by 3DGISKing** [comment]
> Hmmm...
> Do you have any simple ideas how to handle this edge case?

We couldn't help allowing the user to more accurately control.

**Comment by Construkted-Reality** [comment]
> We couldn't help allowing the user to more accurately control.
I don't understand your comment.

**Comment by 3DGISKing** [comment]
I meant all we can do is that we provide the approximate height based on the bounding sphere and allow user to change more accurately.

**Comment by Construkted-Reality** [comment]
Agreed.
What I want to avoid is the asset being below the terrain in and not be visible to the user.
So I would like the lowest point of the bounding box or bounding sphere to be placed on the terrain.
That way the asset will ALWAYS be shown above the terrain.

The user can then adjust for more precise location.
