### ISSUE TITLE
iframe embed not working

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#202]
The embed link does not work.

![image](https://user-images.githubusercontent.com/13057505/111881188-ca24d800-8985-11eb-95fe-105a97b95a9e.png) 
 
Opening up the https://gw3.construkted.com/embed/amlkhycrso2 link, doesn't display anything, and gives some construkted.js errors in the console

![image](https://user-images.githubusercontent.com/13057505/111881247-fc363a00-8985-11eb-8eae-45501073ad7e.png)

**Comment by 3DGISKing** [comment]
fixed.
