### ISSUE TITLE
Embed error

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#203]
When I open an embed link in the browser, there's an error that comes up.
This error only happens on the production site, not on GW3.

https://construkted.com/embed/a73faxnydqk

![image](https://user-images.githubusercontent.com/13057505/111918248-97004880-8a5a-11eb-9886-ecf85eaefee3.png)

**Comment by 3DGISKing** [comment]
it works on my side.
