### ISSUE TITLE
Reduce Bing Maps sessions calls

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#205]
Used more then the allotted quota of 1000 calls for this month for Bing Maps from Cesium.
Need to reduce the amount of Bing Maps session calls. 

Assets which are not geo-referenced should not make a call to Bing Maps. 
Only when asset is geo-referenced, should Bing Maps be loaded.

Information how to fully disable Bing Map calls in Cesium JS.
https://cesium.com/docs/tutorials/optimizing-quotas/#optimizing-bing-maps-sessions

This issue is related to issue https://github.com/Construkted-Reality/construkted_reality/issues/207

**Comment by 3DGISKing** [comment]
done.
