### ISSUE TITLE
Embed display of navigation bar

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#206]
In the Embed display, the navigation bar needs to be removed.

![image](https://user-images.githubusercontent.com/13057505/112311632-4a945300-8c7c-11eb-86d8-14f9bb57e7a1.png)

**Comment by 3DGISKing** [comment]
fixed. please check and let me know.

**Comment by Construkted-Reality** [comment]
Yes, works.
Please push to production server.

**Comment by 3DGISKing** [comment]
ok

**Comment by 3DGISKing** [comment]
updated
