### ISSUE TITLE
Geo-Location workflow

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#207]
When a new asset is uploaded which is not geo-referenced, the asset is loaded without terrain or bing maps.
This will reduce the Bin Maps calls (issue https://github.com/Construkted-Reality/construkted_reality/issues/205) 

## NON geo-referenced asset
Only display a button "Add Geo-Location to asset". 
When button is pressed, display all the geo-location controls. 
Also load terrain and Bing maps 

![image](https://user-images.githubusercontent.com/13057505/112316760-c8a72880-8c81-11eb-884a-caf8e3e2dce2.png)

## Geo-referenced asset
Add extra button at the bottom called "Remove asset Geo-Location". This button removes all geo-reference information from asset.
When button is pressed, display an alert asking the user if they are sure they want to remove the geo-reference data from the asset. The alert should read:
"Are you sure you want to remove the geo-location information for this asset?"
Options should be "Yes" and "No"

![image](https://user-images.githubusercontent.com/13057505/112317067-14f26880-8c82-11eb-9fe9-ae812a7f57b6.png)

**Comment by 3DGISKing** [comment]
Let's say that we uploaded an already georeferenced asset. It has not "asset-geo-location-meta" yet.
What should be removed when the "Remove asset Geo-Location" button is clicked?

**Comment by Construkted-Reality** [comment]
Great question.
For georeferenced assets, the button should be "Reset to asset original Geo-Location"?
What do you think?

**Comment by 3DGISKing** [comment]
Looks meaningful.

**Comment by 3DGISKing** [comment]
Please explain the logic when the user is not the owner of the asset.

**Comment by 3DGISKing** [comment]
please check site.

**Comment by Construkted-Reality** [comment]
Some assets load, but some assets don't load. 
Use this asset to test. https://gw3.construkted.com/asset/3yx6yry34e/
The console shows an error.

![image](https://user-images.githubusercontent.com/13057505/112618801-e6e56380-8dfc-11eb-80f6-be4d0ba78fa3.png)

**Comment by 3DGISKing** [comment]
please recheck. I got 404 error for asset 3yx6yry34e

**Comment by Construkted-Reality** [comment]
Ignore last message.

**Comment by Construkted-Reality** [comment]
I checked. Looks good.

**Comment by Construkted-Reality** [comment]
When asset is geo-located, the "Add Geo-Location to asset" button should be hidden.

![image](https://user-images.githubusercontent.com/13057505/112665626-a6540d00-8e31-11eb-8a17-ded0f31ff302.png)

**Comment by 3DGISKing** [comment]
done
