### ISSUE TITLE
Cesium Ion label

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#209]
1. Display only the round logo on the left side 
Use the URL of https://cesium.com/cesiumjs/
2. Display the "Data attribution" link, but rename it to "Map data attribution"
3. Remove the rest.

![image](https://user-images.githubusercontent.com/13057505/112648331-ce3a7500-8e1f-11eb-92fb-5acd2f815044.png)

**Comment by Construkted-Reality** [comment]
For the left icon, please use this URL  https://cesium.com/cesiumjs/

**Comment by 3DGISKing** [comment]
yes.

**Comment by 3DGISKing** [comment]
fixed.
