### ISSUE TITLE
Geo-Location workflow for geo-referenced 3d tile upload asset 

### ISSUE THREAD

**Issue by Construkted-Reality** [Construkted-Reality/construkted_reality#210]
For uploaded 3D-tiles which already have geo-reference information in tileset.json, the "Remove Asset Geo-Location" button will remove the geo-location information and display it without geo-reference (placed at 0,0, with the grey background)

![image](https://user-images.githubusercontent.com/13057505/112317067-14f26880-8c82-11eb-9fe9-ae812a7f57b6.png)

If the asset is uploaded as a geo-referenced 3D Tile, and is displayed with no geo-reference (at 0,0, with the grey background) the button should read "Reload asset original Geo-Location"

![image](https://user-images.githubusercontent.com/13057505/112894843-62b80800-90aa-11eb-8f97-41c537a3ecf3.png)

**Comment by 3DGISKing** [comment]
Uploading nJWjDpopWW.mp4…

is this what you want?

**Comment by Construkted-Reality** [comment]
You didn't leave a video

**Comment by Construkted-Reality** [comment]
If the asset is uploaded as a geo-referenced 3D Tile, and is displayed with no geo-reference (at 0,0, with the grey background) the button should read "Reload asset original Geo-Location" instead of "Add Geo-Location to asset".

When the button is pressed, the geo-reference information from the tileset.json should be loaded update the asset's location.

![image](https://user-images.githubusercontent.com/13057505/112894843-62b80800-90aa-11eb-8f97-41c537a3ecf3.png)

**Comment by 3DGISKing** [comment]
I see

**Comment by 3DGISKing** [comment]
done.

**Comment by Construkted-Reality** [comment]
When the "Remove Asset Geo-Location" button is pressed, the geo-reference data is not removed from the WP.
Next time I reload asset, the geo-reference data is reloaded.

Please make sure that when the "Remove Asset Geo-Location" button is pressed, the data is updated in the WP custom field.

![Save-asset-location](https://user-images.githubusercontent.com/13057505/113512372-5f050500-9532-11eb-98ae-f7fe507eb078.gif)

**Comment by 3DGISKing** [comment]
I'm going to clarify your mentioning: "When the "Remove Asset Geo-Location" button is pressed, the geo-reference data is not removed from the WP."

Geo-reference data of the given asset(tileset) hasn't to do with WP. It is in the tileset.json.
![image](https://user-images.githubusercontent.com/26606704/113573388-a54e8700-964c-11eb-9c63-ebe89cb7fe67.png)

So we need a flag indicating whether or not we ignore the original geo-reference data.

**Comment by 3DGISKing** [comment]
I'll use a new meta key 'ignore-original-transform'.

**Comment by 3DGISKing** [comment]
please check and let me know.

**Comment by Construkted-Reality** [comment]
Can we not use the `asset_geo-location` meta key to store that value? 

The `asset_geo-location` will have 3 states"
- null (no geo-location information)
- geo-location information
- ignore_original_transform

Is there a reason NOT to use this approach?

**Comment by 3DGISKing** [comment]
I think each meta key must have a clear meaning.

**Comment by 3DGISKing** [comment]
Otherwise, we need to modify a bunch of code.

**Comment by Construkted-Reality** [comment]
Understood.
