### ISSUE TITLE
How is the Cesium Ion tileset location updated?

### ISSUE THREAD

**Issue by max-krichenbauer** [Construkted-Reality/construkted_reality#215]
Hello, and sorry to bother you with a question here.

I was looking through your code and found that you're changing the geo location of a tileset (in geolocation-popup.php ).
I looked at the Cesium Ion REST API documentation ( https://cesium.com/docs/rest-api/ ), but can't see how the geo location of an asset can be changed.
Your function makes an AJAX call to https://construkted.com/wp-admin/admin-ajax.php (in construkted.js ), which is not on the repository.
How do you make the changes to the Cesium Ion asset?

Thank you for your time and help!

Best regards,
Max

**Comment by Construkted-Reality** [comment]
Hi Max,
The Ion asset has a transform matrix property in the end of the tileset.json file.
We don't actually change the tileset.json. We load its info when loading the asset and decide if want to use its own transform matrix or use our own transform matrix to geo-reference the file.

**Comment by max-krichenbauer** [comment]
Thank you for the explanation!
